language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
deploy:
  provider: npm
  email: gerardo+npm@gaderas.com
  api_key:
    secure: rNpl+D7higThrDmVAZsP35MqNuw0UYSEZEp+6zFFnudGTLq7ImbZvPY2QHZxvvyuQfVqEq8/x0RZmbJjtJ7Eclzn7Cx+kcIOoWC7Iyo/GFDuWz1mVWrwPdXmwyAeGZRJEgTCc58kGc63T1o2NQrWZQ+pud3qrmrng2h04q8qZMU=
  on:
    tags: true
    repo: sanx/metalsmith-date-in-filename
