language: node_js
node_js:
- '0.11'
- '0.10'
- '0.12'
deploy:
  provider: npm
  email: gerardo+npm@gaderas.com
  api_key:
    secure: nBrjHt/tmz8eou0+VE8k23aSkEgr6PrraKl7Y9YGauHNMrLV8StEVcrxC46Hk2Sx6p/3Ub+rdTGOzoZD5/ja5E6KsJn/cjyyNTB9OziuzRNR4edbO3BveAXOBJmaMyasMfxz6bDa2dCty6uOZEy+p5OPbDUqRmYN6w/iyD1ItMM=
  on:
    all_branches: true
    tags: true
    repo: sanx/metalsmith-date-in-filename
