language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: gerardo+npm@gaderas.com
  api_key:
    secure: NMtihzxfrXRti+V3Sr5O2FqzaVtc0oEpQd5KwAWJnLym2ncCqLcQwj5hI2IjuD1ln9OZ6DFBS+kgfJhcB35CQhVzvnJvg46+qtsd/kbK4euAnESHI/m7zD69ZZRZCDZfnpU4GKfKsJWn9KFZneg9q5izWG64pzffeDEGqH+l/9o=
  on:
    all_branches: true
    tags: true
    repo: sanx/metalsmith-date-in-filename
