language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: gerardo+npm@gaderas.com
  api_key:
    secure: 5KKqDZ47tmkA8PkYYpyWdXeFGnO6rvFdZTwvg/vuRqt42J+GRi2byBxC7dcj7yfdJ8x36wrmouUStew3YYDKa9esk7Fqy+M/+2KMnfpNeTHSqDS+A1KIdkMK1OgA8W5rpdQglKNPs0ZoxK4MO8TOxBbCTXdTk5FVUQVghe+pkQI=
  on:
    all_branches: true
    tags: true
    repo: sanx/metalsmith-date-in-filename
