language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: gerardo+npm@gaderas.com
  api_key:
    secure: SmxcMYh1rw6deGiW9+n+a76msr7jjJK7eYfREXjNkaRB/TvhLcSh4w9OZyp1S7e/Z8fhtUTpOOmpWJ10KBZtPrLW19Ub62lozUH6PYFkKnryCl82OI2RgjB1DlphacCHLufRFDVT0nH4AH3Ht7QHsSiY0f7dT9kNkFQUJVeMnCI=
  on:
    all_branches: true
    tags: true
    repo: sanx/metalsmith-date-in-filename
